---
- name: stale-issue
  color: "#2ee5b7"
  description: An issue that has not been updated recently and is considered stale.
- name: stale-pr
  color: "#b69ca1"
  description: An pull request that has not been updated recently and is considered stale.
- name: pinned
  color: "#b6f7a1"
  description: This will be ignored by any stale issue or PR evaluation.
- name: question
  color: "#b6f7a1"
  description: question type
- name: wontfix
  color: "#b6f7a1"
  description: This will not be worked on.
- name: duplicate
  color: "#b6f7a1"
  description: This issue or pull request already has prior history.

## the following labels are required by the jenkins PR release drafting
- name: breaking
  color: "#b6f7a1"
  description: Breaking change
- name: major-enhancement
  color: "#b6f7a1"
  description: Major enhancement
- name: feature
  color: "#b6f7a1"
  description: Feature
- name: bug
  color: "#b6f7a1"
  description: Bug
- name: developer
  color: "#b6f7a1"
  description: Developer
- name: dependencies
  color: "#b6f7a1"
  description: Dependency updates
- name: documentation
  color: "#b6f7a1"
  description: Documentation
- name: chore
  color: "#b6f7a1"
  description: Chore
- name: internal
  color: "#b6f7a1"
  description: Internal
- name: test
  color: "#b6f7a1"
  description: Test
