name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - CHANGELOG.md
  # check_run:
  #   types:
  #     - completed

permissions:
  checks: read
  contents: write

# jobs:
#   maven-cd:
#     uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
#     secrets:
#       MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#       MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.interesting-categories.outputs.interesting == 'true' }}
    steps:
      # - name: Verify CI status
      #   uses: jenkins-infra/verify-ci-status-action@v1.2.2
      #   id: verify-ci-status
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     output_result: true

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        id: draft
        # if: steps.verify-ci-status.outputs.result == 'success'
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check interesting categories
        uses: jenkins-infra/interesting-category-action@v1.2.1
        id: interesting-categories
        if: steps.verify-ci-status.outputs.result == 'success'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_DRAFT_BODY: ${{ steps.draft.outputs.body }}

  release:
    runs-on: ubuntu-latest
    needs: [validate]
    if: needs.validate.outputs.should_release == 'true'
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Release
        uses: jenkins-infra/jenkins-maven-cd-action@v1.3.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
